#!/usr/bin/python
# -*- Mode: Python; coding: utf-8; indent-tabs-mode: nil; tab-width: 4 -*-
import MyWindow
from gi.repository import Gtk
import cairo

window = MyWindow.MyWindow()
window.connect("destroy",Gtk.main_quit)
window.set_decorated(False)

window.show()
Gtk.main()
